package database

import (
	"database/sql"
	"fmt"

	_ "github.com/mattn/go-sqlite3"
)

//type Queries struct {
//	db *sql.DB
// other fields as generated by sqlc
//}

var db *sql.DB
var queries *Queries

func OpenDatabase() error {
	var err error
	db, err = sql.Open("sqlite3", "./database.db")
	if err != nil {
		return fmt.Errorf("error unable to connect to db: %w", err)
	}

	err = db.Ping()
	if err != nil {
		return fmt.Errorf("error pinging db: %w", err)
	}

	queries = New(db)

	return nil
}

func GetDB() *sql.DB {
	return db
}

func GetQueries() *Queries {
	return queries
}
