// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type AssignedTask struct {
	AssignedTaskID    int64
	TaskID            int64
	ConnectionID      int64
	WorkerID          int64
	Type              string
	Status            string
	Points            int64
	DurationMinutes   int64
	TimerDays         sql.NullInt64
	TimerHours        sql.NullInt64
	TimerMinutes      sql.NullInt64
	AssignedAt        sql.NullTime
	DueTime           time.Time
	RequiresImage     int64
	NumImagesRequired int64
	RequiresVideo     int64
	NumVideosRequired int64
	RequiresAudio     int64
	NumAudioRequired  int64
	MinWordCount      sql.NullInt64
	PunishmentTaskID  sql.NullInt64
	CompletedAt       sql.NullTime
}

type Connection struct {
	ConnectionID int64
	ManagerID    int64
	WorkerID     int64
	WorkerPoints int64
}

type ConnectionRequest struct {
	RequestID          int64
	SenderID           int64
	ReceiverID         int64
	SuggestedWorkerID  int64
	SuggestedManagerID int64
	IsActive           int64
}

type Session struct {
	SessionID int64
	UserID    int64
	Token     string
	CreatedAt string
	ExpiresAt string
}

type SupportTicket struct {
	TicketID         int64
	UserID           int64
	Email            string
	IssueDescription string
	CreatedAt        sql.NullTime
}

type Task struct {
	TaskID                 int64
	ManagerID              int64
	Title                  string
	Description            sql.NullString
	Type                   string
	DefaultPoints          int64
	DefaultDurationMinutes int64
	TimerDays              sql.NullInt64
	TimerHours             sql.NullInt64
	TimerMinutes           sql.NullInt64
	RequiresImage          int64
	NumImagesRequired      int64
	RequiresVideo          int64
	NumVideosRequired      int64
	RequiresAudio          int64
	NumAudioRequired       int64
	MinWordCount           sql.NullInt64
	PointCost              sql.NullInt64
	IsBookmarked           int64
	RepeatFrequency        sql.NullString
	RepeatConnectionID     sql.NullInt64
	LastAssignedAt         sql.NullTime
	PunishmentTaskID       sql.NullInt64
	CreatedAt              sql.NullTime
}

type TaskSubmission struct {
	SubmissionID   int64
	AssignedTaskID int64
	SubmissionText sql.NullString
	ImagePaths     sql.NullString
	VideoPaths     sql.NullString
	AudioPaths     sql.NullString
	SubmittedAt    sql.NullTime
}

type User struct {
	UserID               int64
	Email                string
	Username             string
	PasswordHash         string
	ActiveConnectionID   sql.NullInt64
	IsMember             int64
	StripeCustomerID     sql.NullString
	StripeSubscriptionID sql.NullString
	SubscriptionStatus   sql.NullString
	CreatedAt            sql.NullTime
}
