// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"
)

type AssignedPunishment struct {
	AssignedPunishmentID int64
	PunishmentID         int64
	WorkerID             int64
	AssignedTaskID       int64
	CompletedAt          sql.NullTime
}

type AssignedTask struct {
	AssignedTaskID int64
	TaskID         int64
	WorkerID       int64
	Points         int64
	DueTime        time.Time
	RequiresImage  bool
	RequiresVideo  bool
	WordCount      sql.NullInt64
	CompletedAt    sql.NullTime
}

type Connection struct {
	ConnectionID int64
	ManagerID    int64
	WorkerID     int64
}

type ConnectionRequest struct {
	RequestID          int64
	SenderID           int64
	RecieverID         int64
	SuggestedWorkerID  int64
	SuggestedManagerID int64
	IsActive           int64
}

type Punishment struct {
	PunishmentID int64
	ManagerID    int64
	Title        string
	Description  sql.NullString
}

type Reward struct {
	RewardID    int64
	ManagerID   int64
	Title       string
	Description sql.NullString
	PointCost   int64
}

type Session struct {
	SessionID int64
	UserID    int64
	Token     string
	CreatedAt string
	ExpiresAt string
}

type Task struct {
	TaskID          int64
	ManagerID       int64
	Title           string
	Description     sql.NullString
	DefaultPoints   int64
	DefaultDuration int64
	RequiresImage   bool
	RequiresVideo   bool
	WordCount       sql.NullInt64
}

type TaskWorkermission struct {
	WorkermissionID   int64
	AssignedTaskID    int64
	WorkermissionTime sql.NullTime
	ImagePath         sql.NullString
	VideoPath         sql.NullString
	TextContent       sql.NullString
}

type User struct {
	UserID             int64
	Email              string
	Username           string
	PasswordHash       string
	ActiveConnectionID int64
	IsMember           int64
	Points             int64
	CreatedAt          sql.NullTime
}
