CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	username VARCHAR(255) UNIQUE NOT NULL,
	email VARCHAR(255) UNIQUE NOT NULL,
	password_hash TEXT NOT NULL,
	role VARCHAR(50) NOT NULL CHECK (role IN ('manager', 'assistant')),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tasks (
	id SERIAL PRIMARY KEY,
	manager_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	assistant_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	title VARCHAR(255) NOT NULL,
	description TEXT,
	due_date TIMESTAMP NOT NULL,
	is_consequence BOOLEAN DEFAULT FALSE,
	parent_task_id INTEGER REFERENCES tasks(id) ON DELETE SET NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE submissions (
	id SERIAL PRIMARY KEY,
	task_id INTEGER NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
	assistant_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	file_url TEXT,
	file_type VARCHAR(50) CHECK (file_type IN ('image', 'audio', 'video')),
	submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
